version: "3"
services:
  hub:
    image: seleniarm/hub:4.1.2-20220227
    ports:
      - "4444:4444"
  chrome:
    image: seleniarm/node-chromium:4.1.2-20220227
    shm_size: '2g'        
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: seleniarm/node-firefox:4.1.2-20220227
    shm_size: '4g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  search-module1:
    image: saranya93/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./output/search-result-from-docker1:/usr/share/udemy/test-output
  search-module2:
    image: saranya93/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - MODULE=search-module.xml
    volumes:
      - ./output/search-result-from-docker2:/usr/share/udemy/test-output
  book-flight-module1:
     image: saranya93/selenium-docker
     depends_on:
       - chrome
       - firefox
     environment:
       - BROWSER=chrome
       - HUB_HOST=hub
       - MODULE=book-flight.xml
     volumes:
       - ./output/bookflight-result-from-docker1:/usr/share/udemy/test-output
  book-flight-module2:
    image: saranya93/selenium-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=book-flight.xml
    volumes:
      - ./output/bookflight-result-from-docker2:/usr/share/udemy/test-output




#Note: Incase we have our selenium set up placed in some other machine we can always remove the hub, chrome, firefox services above and
# replace the HUB_HOST with that machine ip which contains selenium grid set up

#increare the shared memory size shm_size to fix the firefox crash

#Adding multiple xml files/modules in same file to run as suite
# we can add same module for testing different browsers like search-module1 & 2
